# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
 vmImage: 'windows-latest'

variables:
 buildPlatform: 'Any CPU'
 buildConfiguration: 'Release'
 solution: '**/SampleWebApp.sln'
 project: '**/SampleWebApp.csproj'

steps:
- task: NuGetToolInstaller@1
  name: 'NugetToolInstaller'
  displayName: 'Nuget tool Installer'

- task: NuGetCommand@2
  name: 'NugetRestore'
  displayName: 'Nuget restore packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: 'Test'
  displayName: 'Run test'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'
    
- task: DotNetCoreCLI@2
  name: 'Publish'
  displayName: 'Run Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifact'
  displayName: 'Publish Build  Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SampleWebApp'
    publishLocation: 'Container'